[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Proyecto SYAD Trimestre 1"
authors = [{name = "Pablo González", email = "asir2-syad-proy1@gonzaleztroyano.es"}]
dynamic = ["version", "description"]
